### PR TITLE
Make it possible to overwrite the slackistrano hooks

### PR DESCRIPTION
**Pull request by NielsKSchjoedt**

### CODE REVIEW

**Review by dipth — APPROVED** [review]

**Comment by phallstrom** [comment]
I haven't looked at this repo in a long time and just noticed this. Oof. Sorry.  Y'all still want to merge this?

**Comment by autouncle-ci-user** [comment]
sure, thx :-)

**Comment by dipth** [comment]
@phallstrom yes, if you wouldn't mind 🙂

**Comment by NielsKSchjoedt** [comment]
Yes thx :-)

**Review by phallstrom — APPROVED** [review]

**Comment by phallstrom** [comment]
4.0.2 has been released.

**Pull request merged**
