### PR TITLE
Allow posting to several channels

### PR DESCRIPTION
**Pull request by mikz**
Allow posting to several channels by doing:

```ruby
set : slack_channel_updated, %w[#deploy #deploy-production]
```

Also significantly reduces code in all the tasks by using a lambda.
Haven't tried it locally, just edited it on github.

### CODE REVIEW

**Comment by phallstrom** [comment]
Interesting. I like it. Will try to get this merged in soon.

**Comment by mikz** [comment]
@phallstrom awsome, fixed a syntax error and rebased. Will use it in our deployment to try it out.

**Comment by mikz** [comment]
No idea why the build fails. I use ruby 2.2 locally and all works. I'd try to merge #39 first and rebase this PR to get new build.

**Comment by phallstrom** [comment]
Had to tweak the implementation a bit due to some other commits that modified similar sections, but this is in place (soon to be released). Via a555c81f200b65693a995c0c50c734211c3259d7

**Pull request closed without merging**
